#!/usr/bin/env bash
# =============================================================================
# STEP 0 — Create the .env for a target workspace (automates the manual copy+edit).
#
# Generates a CLEAN, source-safe .env from the values you pass as environment
# variables (it does NOT copy .env.example, whose placeholder lines like
# <catalog> / {{secrets/..}} break `source`). The "derived" values that other
# steps discover (PGHOST, ENDPOINT_NAME, PGUSER) are written back automatically
# by steps 01/03 — you never edit .env or app.yaml by hand.
#
# Usage (pass what you know; everything has a sensible default except the profile):
#   DATABRICKS_PROFILE=my-profile \
#   UC_CATALOG=main UC_SCHEMA=default \
#   UAIG_ENDPOINT=databricks-claude-sonnet-5 \
#   APP_NAME=langgraph-sample \
#   bash setup/00_init_env.sh
#
# Re-running is safe: it only overwrites the keys you pass this time.
# =============================================================================
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"

# Defaults so a fresh .env is complete and source-safe even with minimal input.
: "${APP_NAME:=langgraph-sample}"
: "${AGENT_NAME:=langgraph-sample-agent}"
: "${LAKEBASE_PROJECT:=$APP_NAME}"
: "${PGDATABASE:=langgraph_app}"
: "${PGPORT:=5432}"
: "${PGSSLMODE:=require}"
: "${MODEL_SERVICE_AUTH:=token}"
: "${REQUIRE_CALLER_IDENTITY:=false}"
: "${ENABLE_SETUP_ROUTE:=false}"

if [ ! -f "$ENV_FILE" ]; then
  {
    echo "# Generated by setup/00_init_env.sh — workspace-specific values, gitignored."
    echo "# Derived values (PGHOST, PGUSER) are filled in by setup/01 and setup/03."
  } > "$ENV_FILE"
  echo "==> Created a clean .env at ${ENV_FILE}"
else
  echo "==> .env exists — updating only the values you passed"
fi

# Write every configurable key that has a value (defaults applied above). Values
# here are plain identifiers (no spaces/redirection chars) so the file stays
# safe to `source`.
for key in DATABRICKS_PROFILE APP_NAME UAIG_ENDPOINT AGENT_NAME \
           MODEL_SERVICE MODEL_SERVICE_AUTH \
           LAKEBASE_PROJECT PGDATABASE PGPORT PGSSLMODE UC_CATALOG UC_SCHEMA \
           REQUIRE_CALLER_IDENTITY ENABLE_SETUP_ROUTE; do
  if [ -n "${!key:-}" ]; then upsert_env "$key" "${!key}"; fi
done

# ENDPOINT_NAME follows from the Lakebase project name.
upsert_env ENDPOINT_NAME "projects/${LAKEBASE_PROJECT}/branches/production/endpoints/primary"

echo ""
echo "==> .env ready at ${ENV_FILE}"
echo "    Required: DATABRICKS_PROFILE (log in first: databricks auth login --profile <name>)."
echo "    Next: bash setup/deploy_all.sh   (or run 01 -> 03 individually)."
